# Generated by Django 6.0.7 on 2026-07-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('imagem_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planejo Assistir'), ('WATCHING', 'Assistindo'), ('COMPLETED', 'Concluído')], default='PLANNING', max_length=20)),
                ('nota', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
